### ISSUE TITLE
Partial class support

### ISSUE THREAD

**Issue by fasteddys** [efonsecab/AutoGeneratedSystem#3]
Hello, this is a great idea,

1. Partials Class: it would be nice to have partial class support to create custom code as well and maintain aside from the generated code.
2. UI Widgets/View-components/PartialViews/Ajax: Can we also get incremental support for UI Components please like [here](https://github.com/WebVella/TagHelpers) or [TuxBord](https://github.com/jdanylko/Tuxboard)
3. Security at Action level, asp identity at entity or service level
4. Root/[Aggregate ](https://github.com/topics/aggregate-root) objects [Aggregates](https://github.com/charlessolar/Aggregates.NET) or [here](https://github.com/topics/aggregate-root?l=c%23)

Video link is not working, can you please post on youtube

**Comment by efonsecab** [comment]
Hello @fasteddys thanks for the recommendations. 
1. Partial Class: Most of the autogenerated code is already using partial classes, in fact, for most of the autogenerated code, it is required for the developer to manually create the partial class and assign the respective Custom Attribute
<img width="329" alt="image" src="https://user-images.githubusercontent.com/3481899/162751924-82be18bf-8a8a-4b5b-bc26-5d3be2ce8a77.png">
2. UI Widgets/View-components/PartialViews/Ajax: Would you please explain this further, I don't understand what you meant. If you have a use case, please include it in your reply.
3. Security at Action level, asp identity at entity or service level: I have plans to add security, however, it would be at the Controllers level, that way the Services can be reutilized by other administration tools/projects in the solution which can and many times should bypass security.
4. Root/Aggregate objects Aggregates: I do not have experience with this, do you mind to share a use case.

As for the video, please try again in FairPlayTube, we are not uploading any more videos in YouTube in pro of using FairPlayTube which is an platform built in house and more user-centric.

**Comment by fasteddys** [comment]
#2 - In the old scaffold engine, we could scaffold views autoGen with controllers like below pic. Now, with new ASP core we have ViewComponents etc. Since your framework is nice and incremental, we can allow compile time views



     

- [ ]  ![image](https://user-images.githubusercontent.com/96149622/162804489-bf9f366c-9020-46e5-882e-d4e98a307786.png)



______________

Now, in your framework if we had below - then we can generate compile time views also 


 - `[DisplayEntityReadOnly("{entityName}")]` - charts/graphs/tables/front-end content
 - `[DisplayEntityCRUD("{entityName}")]` - you already have the CRUD methods, and you can scaffold those view like ASP CRUD views like this already exists



#4   - root or aggregate objects and business objects that are self contained for e.g. a shopping cart has many oders, address, tax etc its one full root/aggregate objects - [see here nice example](https://codeopinion.com/aggregate-root-design-behavior-data/) ; also I share sample code projects you can use without recoding.

**Comment by efonsecab** [comment]
@fasteddys When you talk about incremental support for UI components and views, do you mean MVC views?
Currently there is CRUD pages automatically generated, but for the Blazor WebAssembly project
<img width="915" alt="image" src="https://user-images.githubusercontent.com/3481899/163013086-f5b2b760-856f-4c1f-92a7-63c4749c901e.png">

**Comment by fasteddys** [comment]
thats correct ASP MVC views
